runtime: nodejs20
instance_class: B1
basic_scaling:
  max_instances: 3
  idle_timeout: 10m
env: standard
runtime_config:
      operating_system: "ubuntu22"
      runtime_version: ">20.0"
service : default
handlers:
  - url: /.*
    secure: always
    script: auto


