runtime: nodejs20
env: standard
runtime_config:
      operating_system: "ubuntu22"
      runtime_version: ">20.0"
service : default
handlers:
  - url: /.*
    secure: always
    script: auto
env_variables:
  DATABASE_USERNAME:"api"
  DATABASE_HOST:34.31.176.85
  DATABASE_PASSWORD:api
  DATABASE_PORT:5432


