name: deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cyresto
    strategy:
      fail-fast: false
      matrix:
        node-version: [20]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 20
    - run: npm ci
    - run: npm run build
    # - name: 'Create GAC File'
    #   uses: jsdaniell/create-json@1.1.2
    #   with:
    #     name: "key.json"
    #     json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with: 
        credentials_json: ${{ secrets.DEPLOY_KEY_FILE_PRODUCTION }}
    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    - name: Deploy
      uses: google-github-actions/deploy-appengine@v0
      with:
        deliverables: app.yaml
        version: v1